name: truebpm
description: "This is a mobile application for the TrueBPM project"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.0+15

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.1
  http: ^1.1.0
  cookie_jar: ^4.0.8
  dio: ^5.4.0
  dio_cookie_manager: ^3.1.1
  logger: ^2.5.0
  provider: ^6.1.2
  get_it: ^8.2.0
  skeletonizer: ^2.0.1
  carousel_slider: ^5.1.1
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.1.0
  animations: ^2.0.11
  url_launcher: ^6.3.1
  flutter_animate: ^4.5.2
  intl: ^0.20.2
  flutter_html: ^3.0.0
  image_picker: ^1.0.7
  image_cropper: ^9.1.0
  image: ^4.2.0
  file_picker: ^10.3.2
  path_provider: ^2.1.3
  permission_handler: ^12.0.1
  device_info_plus: ^11.5.0
  http_parser: ^4.0.2
  shared_preferences: ^2.3.2
  local_auth: ^2.1.6
  photo_view: ^0.15.0
  open_filex: ^4.4.0
  uuid: ^4.5.1
  fl_chart: ^0.69.2
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # integration_test:
  #   sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logos/
    # - assets/icons/
    # - assets/fonts/
    # - assets/sounds/
    # - assets/videos/
